bibe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/',include('dashboard.urls')), 
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  # Include URLs of other apps
    path('conversation/', include('conversation.urls')),
    path('cart/', include('cart.urls', namespace='cart')),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "cart"

urlpatterns = [
    path("add/<item_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:cart_item_id>/", views.remove_from_cart, name="remove_from_cart"),
    path("", views.cart_detail, name="cart_detail"),
    path("checkout/", views.checkout, name='checkout'),
    path("place_order/", views.place_order, name='place_order'),
    path('thank_you/', views.thank_you, name='thank_you'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import  path

from .views import logout_view
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login' ),
    path('logout/', logout_view, name='logout'),
]

cart/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.CharField(max_length=255)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.quantity} x {self.product}"

    def get_absolute_url(self):
        return reverse("cart:cart_detail")
    
    def total_price(self):
        return self.quantity * self.price
    
    def subtotal(self):
        return self.total_price()
    
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='cart_items', on_delete=models.CASCADE)

cart/views.py
from decimal import Decimal
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import F, Sum

from item.models import Item
from .models import Cart


@login_required
def add_to_cart(request, item_id):
    if request.method == 'POST':
        item = Item.objects.get(pk=item_id)
        quantity = int(request.POST.get('quantity', 1))
        price = item.price  # Fetching the price from the Item object
        
        # Create or update the cart item
        cart_item, created = Cart.objects.get_or_create(
            user=request.user,
            product=item,  # Assuming 'product' is the correct field name in Cart model
            defaults={'quantity': quantity, 'price': price}
        )

        if not created:
            # If the item already exists in the cart, update the quantity
            cart_item.quantity = F('quantity') + quantity
            cart_item.save()

        messages.success(request, f"{quantity} {item.name}{'s' if quantity > 1 else ''} added to your cart.")

        return redirect("cart:cart_detail")

    else:
        # If the request method is not POST, handle the error or redirect appropriately
        messages.error(request, "Invalid request method.")
        return redirect("item:items")

@login_required
def remove_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(Cart, id=cart_item_id)

    if cart_item.user == request.user:
        cart_item.delete()
        messages.success(request, "Item removed from your cart.")

    return redirect("cart:cart_detail")

@login_required
def cart_detail(request):
    # Retrieve cart items associated with the current user
    cart_items = Cart.objects.filter(user=request.user)

    # Calculate total price using aggregation
    total_price = cart_items.aggregate(total_price=Sum(F('price') * F('quantity')))['total_price'] or Decimal(0)

    context = {
        'cart_items': cart_items,
        'total_price': total_price,
    }
    return render(request, 'cart/cart_detail.html', context)

def calculate_total_price(cart_items):
    total_price = 0
    for item in cart_items:
        total_price += item.quantity * item.price
    return total_price


@login_required
def checkout(request):
    if request.method == 'POST':
        # Process the form data if POST request
        # Assuming you have code here to process the form data

        # Redirect to a thank you page or some other page
        return render(request, 'cart/checkout.html')

    else:
        # If the request method is GET, render the checkout page
        user_cart = Cart.objects.filter(user=request.user)
        
        # Calculate total price
        total_price = calculate_total_price(user_cart)
        
        # Get the shipping address from the request.POST data
        shipping_address = request.POST.get('shipping_address', '')

        context = {
            'user_cart': user_cart,
            'total_price': total_price,
            'shipping_address': shipping_address,
        }
        return render(request, 'cart/checkout.html', context)
    
    
def place_order(request):
    if request.method == 'POST':
        # Process the form data if POST request
        # Assuming you have code here to process the form data

        # Redirect to a thank you page or some other page
        return render(request, 'cart/place_order.html')

    else:
        # If the request method is GET, render the place order page
        # Retrieve the shipping address from the request.GET data
        shipping_address = request.GET.get('shipping_address', '')

        context = {
            'shipping_address': shipping_address,
        }

        return render(request, 'cart/place_order.html', context)


@login_required
def thank_you(request):
    # Clear the user's cart after checkout
    user_cart = Cart.objects.filter(user=request.user)
    user_cart.delete()

    return render(request, 'cart/thank_you.html')

def view_cart(request):
    cart_items = Cart.objects.filter(user=request.user)
    total_price = sum(item.quantity * item.price for item in cart_items)
    context = {
        'cart_items': cart_items,
        'total_price': total_price,
    }
    return render(request, 'cart/cart.html', context)

cart/templates/cart/add_to_cart.html
{% extends 'core/base.html' %}


{% block content %}    
    {{ message }}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Add to Cart">
    </form>
{% endblock %}

cart/templates/cart/cart_detail.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
    {% if cart_items %}
        <div class="flex justify-center">
            <div class="w-full lg:w-2/3">
                <table class="min-w-full">
                    <thead>
                        <tr>
                            <th class="px-4 py-2">Product</th>
                            <th class="px-4 py-2">Quantity</th>
                            <th class="px-4 py-2">Price per Item</th>
                            <th class="px-4 py-2">Total Price</th>
                            <th class="px-4 py-2"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in cart_items %}
                        <tr>
                            <td class="px-4 py-2">
                                <div class="flex items-center">
                                    <img src="{{ item.image.url }}" alt="{{ item.name }}" class="h-10 w-10 mr-2">
                                    <span>{{ item.product }}</span>
                                </div>
                            </td>
                            <td class="px-4 py-2">{{ item.quantity }}</td>
                            <td class="px-4 py-2">{{ item.price }}</td>
                            <td class="number">{{ item.subtotal }}</td>
                            <td class="px-4 py-2"><a href="{% url 'cart:remove_from_cart' item.id %}" class="text-red-500 hover:text-red-700">Remove</a></td>
                        </tr> 
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3"></td>
                            <td class="px-4 py-2 font-bold">Total:</td>
                            <td class="px-4 py-2 font-bold">{{ total_price|floatformat:2 }}</td>
                        </tr>
                    </tfoot>
                </table>

                <a href="{% url 'cart:checkout' %}" class="block w-full max-w-xs mx-auto mt-4 py-2 px-4 bg-blue-500 text-white text-center rounded hover:bg-blue-700">Checkout</a>
            </div>
        </div>
    {% else %}
        <p class="text-center mt-8">Your shopping cart is empty.</p>
    {% endif %}
{% endblock %}

cart/templates/cart/checkout.html
{% extends 'core/base.html' %}

{% load custom_filters %}

{% block title %}Checkout{% endblock %}

{% block content %}
  <h1 class="text-3xl font-bold mb-4">Checkout</h1>
  
  <div class="flex">
    <!-- Address Information -->
    <div class="w-1/2 mr-8">
      <h2 class="text-xl font-semibold mb-4">Shipping Address</h2>
      <div class="mb-4">
        <label for="name_in_card" class="block text-gray-700 text-sm font-bold mb-2">Name in card</label>
        <input type="text" id="name_in_card" name="name_in_card" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="mb-6">
        <label for="shipping_address" class="block text-gray-700 text-sm font-bold mb-2">Shipping Address</label>
        <input type="text" id="shipping_address" name="shipping_address" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
    </div>
    
    <!-- Card Information -->
    <div class="w-1/2">
      <h2 class="text-xl font-semibold mb-4">Card Information</h2>
      <div class="mb-6">
        <label for="card_number" class="block text-gray-700 text-sm font-bold mb-2">Card Number</label>
        <input id="card_number" type="tel" inputmode="numeric" pattern="[0-9\s]{16}" 
           autocomplete="cc-number" maxlength="19" 
           placeholder="xxxx xxxx xxxx xxxx" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="mb-6">
        <label for="card_cvc" class="block text-gray-700 text-sm font-bold mb-2">CVC</label>
        <input id="card_cvc" type="tel" inputmode="numeric" pattern="[0-9\s]{3}" 
           autocomplete="cvc-number" maxlength="3" 
           placeholder="xxx" required class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
      </div>
      <div class="mb-6">
        <label for="card_expiry" class="block text-gray-700 text-sm font-bold mb-2">Card Expiry (MM/YYYY)</label>
        <input type="text" id="card_expiry" name="card_expiry" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" placeholder="MM/YYYY">
      </div>
    </div>
  </div>
  
  <!-- Checkout Button -->
  <form action="{% url 'cart:place_order' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Place Order</button>
  </form>
{% endblock %}

cart/templates/cart/place_order.html
{% extends 'core/base.html' %}

{% block title %}Place Order{% endblock %}

{% block content %}
<div class="container mx-auto px-4 py-8">
  <h1 class="text-3xl font-bold mb-4">Place Order</h1>
  
  <div class="mb-8">
    <h2 class="text-xl font-semibold mb-2">Shipping Address</h2>
    <p>{{ shipping_address }}</p>
    <li class="mb-2">Total Price: ${{ total_price }}</li>
  </div>

  <!-- Confirm Order Button -->
  <form action="{% url 'cart:thank_you' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded">Confirm Order</button>
  </form>
</div>
{% endblock %}

cart/templates/cart/remove_from_cart.html
{% extends 'core/base.html' %}

{% block content %}
   
    {{ message }}

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Remove from Cart">
    </form>
{% endblock %}

cart/templates/cart/thank_you.html
{% extends 'core/base.html' %}

{% block title %}THANK YOU!{% endblock %}

{% block content %}
  <h1>Thank You for Your Order!</h1>
  <br>
  <br>
  
  <!-- Add any additional content you want to display on the thank you page -->
  
  <!-- Button to go to homepage -->
  <a href="{% url 'core:index' %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4">Go to Homepage</a>
  
{% endblock %}